routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnswerController;


Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/profile', [ProfileController::class, 'storeModules'])->name('profile.store.modules');
    Route::resource('modules', ModuleController::class);
    Route::resource('question', QuestionController::class)->except('create');
    Route::get('/question/create/{module_id}',[QuestionController::class,'create'])->name('question.create');
    Route::post('/question/update/{answer}',[AnswerController::class,'update'])->name('answer.update');
    Route::get("/question/{question}/answer", [AnswerController::class, 'create'])->name('answer.question');
    Route::post("/answer", [AnswerController::class, 'store'])->name('answer.store');
    Route::get("/questions-pending/module/{module_id}", [QuestionController::class,'pending'])->name('question.pending');
});


require __DIR__.'/auth.php';

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Laravel\Scout\Searchable;
/**
 *
 * @OA\Schema(
 * required={"password"},
 * @OA\Xml(name="Question"),
 * @OA\Property(property="id", type="integer", example="1"),
 * @OA\Property(property="title", type="string", description="Question title", example="¿Is laravel a framework?"),
 * @OA\Property(property="description", type="string", description="Question description", example="I'm wondering if laravel is a framework or a language"),
 * @OA\Property(property="photo", type="string", description="Photo about question", example="img/5fJgbx4qSU.png"),
 * @OA\Property(property="module_id", type="integer", example="4"),
 * @OA\Property(property="user_id", type="integer", example="2")
 * )
*/
class Question extends Model
{
    use HasFactory;
    use Searchable;

    protected $guarded = [
        'id',
    ];

    public function answer(): HasOne
    {
        return $this->hasOne(Answer::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class)->withDefault(); // withDefault se usa por si no encuentra
    }
}

app/Http/Controllers/Api/QuestionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Question;
use Illuminate\Http\Request;

/**
 * @OA\Post(
 * path="/api/questions",
 * summary="Create a new question",
 * description="Create a new question",
 * security={ {"apiAuth": {} }},
 * operationId="QuestionStore",
 * tags={"questions"},
 * @OA\RequestBody(
 *    required=true,
 *    description="Create a new question",
 *    @OA\JsonContent(
 *         ref="#/components/schemas/Question"
 *      )
 * ),
 * @OA\Response(
 *    response=422,
 *    description="Wrong credentials response",
 *    @OA\JsonContent(
 *       @OA\Property(property="message", type="string", example="Sorry, wrong email address or password. Please try again")
 *        )
 *     ),
 * @OA\Response(
 *     response=200,
 *     description="Question create successfully",
 *     @OA\JsonContent(
 *       @OA\Property(property="message", type="string", example="Question create!")
 *        )
 *     ),
 * )
 *
 */

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $questions = Question::get();
        return $questions;
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request-> validate([
            'title' => 'required|string|max:255',
            'description' => 'required|string|max:255',
            /*'photo' => 'nullable|mimes:jpg,bmp,png,',*/
            'module_id' => 'required|integer|exists:modules,id',
            'user_id' => 'required|integer|exists:users,id'
        ]);

        $question = new Question();
        $question->title = $request->title;
        $question->description = $request->description;
        $question->photo = $request->photo;
        $question->module_id = $request->module_id;
        $question->user_id = $request->user_id;
        $question->save();
        return response()->json($question, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(Question $question)
    {
        return response()->json($question, 200);
    }

    public function showPending(Question $question)
    {
        return response()->json($question, 200);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Question $question)
    {
        $question->title = $request->title;
        $question->description = $request->description;
        $question->photo = $request->photo;
        $question->module_id = $request->module_id;
        $question->user_id = $request->user_id;
        $question->save();
        return response()->json($request);

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question)
    {
        $question->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;
use App\Models\Question;
use Dotenv\Exception\ValidationException;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;



class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $user_id = Auth::user()->id;
        $myQuestions = Question::where("user_id", "=", $user_id)->orderBy("created_at", "desc")->paginate(10);
        $title = "My questions";
        $areMyQuestions = true;
        $module_id = null;
        $pending = false;
        return view("questions.index", compact("myQuestions",  "title", "areMyQuestions", "module_id", "pending"));
    }

    public function pending($module_id)
    {
        $title = ucfirst(Module::find($module_id)->name);

        $myQuestions = Question::whereDoesntHave('answer')->where('module_id', "=", $module_id)->orderBY('created_at')->paginate(10);
        $areMyQuestions = false;
        $pending = true;
        return view('questions.index', compact('myQuestions', 'title', 'module_id', 'areMyQuestions', 'pending'));

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create($module_id)
    {
        return view("questions.create",compact('module_id'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        try {
            $validatedData = $request->validate([
                "module_id" => "required|exists:modules,id",
                "title" => "required|string|max:255",
                "description" => "required|string",
                "photo" => "nullable|mimes:jpg,bmp,png",
            ]);
            $user_id = Auth::user()->id;
            $validatedData["user_id"] = $user_id;
            if ($request->has("photo")) {
                $extension = $request->photo->extension();
                $path = $request->photo->storeAs("img", substr(str_replace(["+", "/", "="],  "", base64_encode(random_bytes(10))), 0, 10) . "." . $extension,'public');
                $validatedData["photo"] = $path;
            }
            Question::create($validatedData);
            return back();
        } catch (ValidationException $e) {
            return $e->getMessage();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(int $module_id)
    {
        $myQuestions = Question::where("module_id", "=", $module_id)->orderBy("created_at", "desc")->paginate(10);
        $title = Module::find($module_id)->name;
        $areMyQuestions = false;
        $pending = false;
        return view("questions.index", compact("myQuestions", "title", "module_id", "areMyQuestions", 'pending'));

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Question $question)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Question $question)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question)
    {
        $question->delete();
        return back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\Support\Facades\Auth;
use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        $user = Auth::user();
        $modules = $user->modules;
        return view('layouts.app', compact("modules"));
    }
}

resources/views/questions/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('New question') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-xl">

                    <form method="post" action="{{ route('question.store') }}" class="mt-6 space-y-6"
                        enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="module_id" value="{{$module_id}}" />
                        <div>
                            <x-input-label for="title" :value="__('Title')" />
                            <x-text-input id="title" name="title" type="text" class="mt-1 block w-full" required autofocus autocomplete="title" />
                            <x-input-error class="mt-2" :messages="$errors->get('title')" />
                        </div>

                        <div>
                            <x-input-label for="description" :value="__('Description')" />
                            <x-text-input id="description" name="description" type="text" class="mt-1 block w-full" required />
                            <x-input-error class="mt-2" :messages="$errors->get('description')" />
                        </div>

                        <div>
                            <x-input-label for="photo" :value="__('Photo')" />
                            <x-text-input id="photo" name="photo" type="file" class="mt-1 block w-full" />
                            <x-input-error class="mt-2" :messages="$errors->get('photo')" />
                        </div>

                        <div class="flex items-center gap-4">
                            <x-primary-button>{{ __('Save') }}</x-primary-button>
                        </div>
                    </form>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/questions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __($title) }}
        </h2>
        @if(Auth::user()->role === "user_role")
            @isset($module_id)
                <x-nav-link :href="route('question.create',$module_id)" :active="request()->routeIs('question.create')">
                    {{ __('New question') }}
                </x-nav-link>
            @endisset
        @endif

        <livewire:search-question :areMyQuestions="$areMyQuestions" :module_id="$module_id" :pending="$pending"></livewire:search-question>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <div class="p-6 text-gray-900 dark:text-gray-100">
                        <ul>
                            @if(count($myQuestions) === 0)
                                <p>Por el momento no hay niguna cuestión</p>
                            @endif
                            @foreach($myQuestions as $question)
                                    @php($userId = Auth::user()->id)
                                <li class="mb-6">
                                    <h4 class="text-2xl font-bold dark:text-white">{{$question->title}}</h4>
                                    <div>
                                        <small class="block text-sm">Pregunta realizar por:
                                            @if($question->user_id === $userId)
                                                Yo
                                            @else
                                                {{$question->user->name}}
                                            @endif
                                        </small>
                                        <p class="ml-3 block text-lg">{{$question->description}}</p>
                                        <img class="mx-auto rounded-lg" src="{{asset('storage/'.$question->photo)}}" alt="img de la consulta">
                                        @isset($question->answer->content)
                                            <small class="block text-sm">Ha respondido:
                                                {{$question->answer->user_id === $userId ? "Yo" : $question->answer->user->name}}
                                            </small>
                                            <blockquote class="ml-3 text-base">{{$question->answer->content}}</blockquote>
                                        @else
                                            <blockquote class="ml-3">Sin respuesta</blockquote>
                                        @endif

                                        @if($question->user_id === $userId)
                                            <form action="{{ route("question.destroy", $question->id) }}" method="POST" class="mt-2">
                                                @csrf
                                                @method("DELETE")
                                                <button type="submit" class="bg-red-600 p-2 rounded-md">
                                                    <p>Delete</p>
                                                </button>
                                            </form>
                                        @endif
                                        @if(Auth::user()->role === "teacher_role")
                                            <a href="{{route("answer.question", $question)}}" class="mt-2">
                                                <x-primary-button class="p-2 rounded-md" type="button">
                                                    @isset($question->answer->content)
                                                        Editar respuesta
                                                    @else
                                                        Responder
                                                    @endif
                                                </x-primary-button>
                                            </a>
                                        @endif

                                    </div>
                                </li>
                            @endforeach
                        </ul>
                        {{$myQuestions->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>