routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\QuestionController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnswerController;


Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/profile', [ProfileController::class, 'storeModules'])->name('profile.store.modules');
    Route::resource('modules', ModuleController::class);
    Route::resource('question', QuestionController::class)->except('create');
    Route::get('/question/create/{module_id}',[QuestionController::class,'create'])->name('question.create');
    Route::post('/question/update/{answer}',[AnswerController::class,'update'])->name('answer.update');
    Route::get("/question/{question}/answer", [AnswerController::class, 'create'])->name('answer.question');
    Route::post("/answer", [AnswerController::class, 'store'])->name('answer.store');
    Route::get("/questions-pending/module/{module_id}", [QuestionController::class,'pending'])->name('question.pending');
});


require __DIR__.'/auth.php';

app/Models/Module.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 *
 * @OA\Schema(
 * required={"password, id, name, description"},
 * @OA\Xml(name="Module"),
 * @OA\Property(property="id", type="integer", example="1"),
 * @OA\Property(property="name", type="string", description="Short name of the module", example="DIW"),
 * @OA\Property(property="description", type="string", description="Full name of the module",example="Diseña de Interfaces Web"),
 * )
 */

class Module extends Model
{

    public $timestamps = false;

    use HasFactory;

    protected $guarded = ['id'];
}

app/Http/Controllers/Api/ModuleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Module;
use Illuminate\Http\Request;

/**
 * @OA\Post(
 * path="/api/modules",
 * summary="Create a new module",
 * description="Create a new module",
 * security={ {"apiAuth": {} }},
 * operationId="ModuleStore",
 * tags={"modules"},
 * @OA\RequestBody(
 *    required=true,
 *    description="Create a new module",
 *    @OA\JsonContent(
 *         ref="#/components/schemas/Module"
 *      )
 * ),
 * @OA\Response(
 *    response=422,
 *    description="Wrong credentials response",
 *    @OA\JsonContent(
 *       @OA\Property(property="message", type="string", example="Sorry, wrong email address or password. Please try again")
 *        )
 *     ),
 * @OA\Response(
 *     response=200,
 *     description="Question create successfully",
 *     @OA\JsonContent(
 *       @OA\Property(property="message", type="string", example="Module create!")
 *        )
 *     ),
 * )
 *
 *
 * @OA\Delete(
 *   path="/api/modules",
 *   summary="Delete an existing module",
 *   description="Delete an existing module",
 *   security={ {"apiAuth": {} }},
 *   operationId="ModuleDestroy",
 *   tags={"modules"},
 *   @OA\Response(
 *        response=401,
 *        description="Error: Unauthorized",
 *        @OA\JsonContent(
 *        @OA\Property(property="message", type="string", example="Unauthenticated")
 *            )
 *   ),
 *   @OA\Response(
 *        response=204,
 *        description="Module deleted successfully"
 *    )
 *  )
 */

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $module = Module::get();
        return $module;
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'description' => 'required|string|max:255'
        ]);
        $module = new Module();
        $module->name = $request->name;
        $module->description = $request->description;
        $module->save();
        return response()->json($request, 201);
    }

    /**
     * Display the specified resource.
     */
    public function show(Module $module)
    {
        return response()->json($module,200);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Module $module)
    {
        $module->name = $request->name;
        $module->description = $request->description;
        $module->save();
        return response()->json($request);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Module $module)
    {
        $module->delete();
        return response()->json(null, 204);
    }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Module;
use Illuminate\Http\Request;

class ModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $modules = Module::all();
        return view('modules.index', compact('modules'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('modules.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            "name" => "required|string|max:255",
            "description" => "required|string|max:255",
        ]);

        Module::create($validatedData);

        return redirect()->route('modules.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Module $module)
    {
        return view('modules.show', compact('module'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Module $module)
    {
        return view('modules.create', compact('module'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Module $module)
    {
        $rules = [];

        if ($request->has('name')) {
            $rules['name'] = 'required|string|max:255';
        }

        if ($request->has('description')) {
            $rules['description'] = 'required|string|max:255';
        }

        $validatedData = $request->validate($rules);

        $module->update($validatedData);
        return redirect()->route('modules.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Module $module)
    {
        $module->delete();
        return back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\Support\Facades\Auth;
use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        $user = Auth::user();
        $modules = $user->modules;
        return view('layouts.app', compact("modules"));
    }
}

resources/views/modules/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Modules') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <form action="{{ isset($module) ? route('modules.update', $module) : route('modules.store') }}"
                        method="POST">
                        @csrf
                        @if (isset($module)) @method('PATCH')
                        @endif

                        <h1 class="pb-12 text-3xl">{{ isset($module) ? 'Editar' : 'Nuevo' }} Modulo</h1>

                        <div class="mb-4">
                            <label for="name"
                                class="block text-gray-700 dark:text-gray-300 font-bold mb-2">Name</label>
                            <input type="text" name="name"
                                value="{{ isset($module) ? $module->name : old('name') }}"
                                class="block appearance-none border rounded text-gray-700 leading-tight">

                            @error('name')
                                <small class="text-red-600">{{ $message }}</small>
                            @enderror
                        </div>

                        <div class="mb-4">
                            <label for="description"
                                class="block text-gray-700 dark:text-gray-300 font-bold mb-2">Description</label>
                            <input type="text" name="description"
                                value="{{ isset($module) ? $module->description : old('description') }}"
                                class="block appearance-none border rounded w-full text-gray-700 leading-tight">

                            @error('description')
                                <small class="text-red-600">{{ $message }}</small>
                            @enderror
                        </div>

                        <button type="submit"
                            class="py-3 px-4 mt-12 bg-green-400 hover:bg-green-500 rounded-full dark:text-black">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/modules/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Modules') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <table>
                        <thead>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Actions</th>
                        </thead>
                        <tbody>
                        @foreach($modules as $module)
                            <tr>
                                <td>{{ $module->id }}</td>
                                <td>{{ $module->name }}</td>
                                <td>{{ $module->description }}</td>
                                <td>
                                    <a href="{{ route("modules.show", $module->id) }}">show</a>
                                </td>
                                <td>
                                    <a href="{{ route('modules.edit', $module) }}">edit</a>
                                </td>
                                <td>
                                    <form action="{{ route("modules.destroy", $module->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit">
                                            <img src="" alt="delete" height="20" width="20">
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <a href="{{ route('modules.create') }}" class="p-4 ml-12 bg-sky-500 hover:bg-sky-600 rounded-full">Añadir
        Módulo</a>
</x-app-layout>

resources/views/modules/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Show module') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 dark:text-gray-100">
                    <h2 class="text-xl">{{ $module->name }}</h2>
                    <p>{{ $module->description }}</p>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>